"""Initial migration with quick_store prefix

Revision ID: 40830494e3af
Revises: 
Create Date: 2026-01-04 00:27:05.024907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40830494e3af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_store__companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency_symbol', sa.String(), nullable=False),
    sa.Column('max_stores', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quick_store__stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['quick_store__companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__stores_company_id'), 'quick_store__stores', ['company_id'], unique=False)
    op.create_table('quick_store__users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['quick_store__companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__users_email'), 'quick_store__users', ['email'], unique=True)
    op.create_index(op.f('ix_quick_store__users_username'), 'quick_store__users', ['username'], unique=True)
    op.create_table('quick_store__combos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['quick_store__stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__combos_store_id'), 'quick_store__combos', ['store_id'], unique=False)
    op.create_table('quick_store__customer_names',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['quick_store__stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='unique_store_customer')
    )
    op.create_index(op.f('ix_quick_store__customer_names_store_id'), 'quick_store__customer_names', ['store_id'], unique=False)
    op.create_table('quick_store__orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['quick_store__users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['quick_store__stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__orders_created_at'), 'quick_store__orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_quick_store__orders_store_id'), 'quick_store__orders', ['store_id'], unique=False)
    op.create_table('quick_store__products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['quick_store__stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__products_store_id'), 'quick_store__products', ['store_id'], unique=False)
    op.create_table('quick_store__sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['quick_store__stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', name='unique_store_date')
    )
    op.create_index(op.f('ix_quick_store__sessions_date'), 'quick_store__sessions', ['date'], unique=False)
    op.create_index(op.f('ix_quick_store__sessions_store_id'), 'quick_store__sessions', ['store_id'], unique=False)
    op.create_table('quick_store__combo_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('combo_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['quick_store__combos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['quick_store__products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__combo_items_combo_id'), 'quick_store__combo_items', ['combo_id'], unique=False)
    op.create_table('quick_store__order_edit_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=False),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['quick_store__users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['quick_store__orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__order_edit_history_order_id'), 'quick_store__order_edit_history', ['order_id'], unique=False)
    op.create_table('quick_store__order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['quick_store__orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['quick_store__products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_store__order_items_order_id'), 'quick_store__order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quick_store__order_items_order_id'), table_name='quick_store__order_items')
    op.drop_table('quick_store__order_items')
    op.drop_index(op.f('ix_quick_store__order_edit_history_order_id'), table_name='quick_store__order_edit_history')
    op.drop_table('quick_store__order_edit_history')
    op.drop_index(op.f('ix_quick_store__combo_items_combo_id'), table_name='quick_store__combo_items')
    op.drop_table('quick_store__combo_items')
    op.drop_index(op.f('ix_quick_store__sessions_store_id'), table_name='quick_store__sessions')
    op.drop_index(op.f('ix_quick_store__sessions_date'), table_name='quick_store__sessions')
    op.drop_table('quick_store__sessions')
    op.drop_index(op.f('ix_quick_store__products_store_id'), table_name='quick_store__products')
    op.drop_table('quick_store__products')
    op.drop_index(op.f('ix_quick_store__orders_store_id'), table_name='quick_store__orders')
    op.drop_index(op.f('ix_quick_store__orders_created_at'), table_name='quick_store__orders')
    op.drop_table('quick_store__orders')
    op.drop_index(op.f('ix_quick_store__customer_names_store_id'), table_name='quick_store__customer_names')
    op.drop_table('quick_store__customer_names')
    op.drop_index(op.f('ix_quick_store__combos_store_id'), table_name='quick_store__combos')
    op.drop_table('quick_store__combos')
    op.drop_index(op.f('ix_quick_store__users_username'), table_name='quick_store__users')
    op.drop_index(op.f('ix_quick_store__users_email'), table_name='quick_store__users')
    op.drop_table('quick_store__users')
    op.drop_index(op.f('ix_quick_store__stores_company_id'), table_name='quick_store__stores')
    op.drop_table('quick_store__stores')
    op.drop_table('quick_store__companies')
    # ### end Alembic commands ###
